In [1]:
import data_prep
import pandas as pd
import numpy as np

In [2]:
dtypes = {
        'Src IP': 'category',
        'Src Port': 'uint16',
        'Dst IP': 'category',
        'Dst Port': 'uint16',
        'Protocol': 'category',
        'Flow Duration': 'uint32',
        'Tot Fwd Pkts': 'uint32',
        'Tot Bwd Pkts': 'uint32',
        'TotLen Fwd Pkts': 'float32',
        'TotLen Bwd Pkts': 'float32',
        'Fwd Pkt Len Max': 'float32',
        'Fwd Pkt Len Min': 'float32',
        'Fwd Pkt Len Mean': 'float32',
        'Fwd Pkt Len Std': 'float32',
        'Bwd Pkt Len Max': 'float32',
        'Bwd Pkt Len Min': 'float32',
        'Bwd Pkt Len Mean': 'float32',
        'Bwd Pkt Len Std': 'float32',
        'Flow Byts/s': 'float32',
        'Flow Pkts/s': 'float32',
        'Flow IAT Mean': 'float32',
        'Flow IAT Std': 'float32',
        'Flow IAT Max': 'float32',
        'Flow IAT Min': 'float32',
        'Fwd IAT Tot': 'float32',
        'Fwd IAT Mean': 'float32',
        'Fwd IAT Std': 'float32',
        'Fwd IAT Max': 'float32',
        'Fwd IAT Min': 'float32',
        'Bwd IAT Tot': 'float32',
        'Bwd IAT Mean': 'float32',
        'Bwd IAT Std': 'float32',
        'Bwd IAT Max': 'float32',
        'Bwd IAT Min': 'float32',
        'Fwd PSH Flags': 'category',
        'Bwd PSH Flags': 'category',
        'Fwd URG Flags': 'category',
        'Bwd URG Flags': 'category',
        'Fwd Header Len': 'uint32',
        'Bwd Header Len': 'uint32',
        'Fwd Pkts/s': 'float32',
        'Bwd Pkts/s': 'float32',
        'Pkt Len Min': 'float32',
        'Pkt Len Max': 'float32',
        'Pkt Len Mean': 'float32',
        'Pkt Len Std': 'float32',
        'Pkt Len Var': 'float32',
        'FIN Flag Cnt': 'category',
        'SYN Flag Cnt': 'category',
        'RST Flag Cnt': 'category',
        'PSH Flag Cnt': 'category',
        'ACK Flag Cnt': 'category',
        'URG Flag Cnt': 'category',
        'CWE Flag Count': 'category',
        'ECE Flag Cnt': 'category',
        'Down/Up Ratio': 'float32',
        'Pkt Size Avg': 'float32',
        'Fwd Seg Size Avg': 'float32',
        'Bwd Seg Size Avg': 'float32',
        'Fwd Byts/b Avg': 'uint32',
        'Fwd Pkts/b Avg': 'uint32',
        'Fwd Blk Rate Avg': 'uint32',
        'Bwd Byts/b Avg': 'uint32',
        'Bwd Pkts/b Avg': 'uint32',
        'Bwd Blk Rate Avg': 'uint32',
        'Subflow Fwd Pkts': 'uint32',
        'Subflow Fwd Byts': 'uint32',
        'Subflow Bwd Pkts': 'uint32',
        'Subflow Bwd Byts': 'uint32',
        'Init Fwd Win Byts': 'uint32',
        'Init Bwd Win Byts': 'uint32',
        'Fwd Act Data Pkts': 'uint32',
        'Fwd Seg Size Min': 'uint32',
        'Active Mean': 'float32',
        'Active Std': 'float32',
        'Active Max': 'float32',
        'Active Min': 'float32',
        'Idle Mean': 'float32',
        'Idle Std': 'float32',
        'Idle Max': 'float32',
        'Idle Min': 'float32',
        'Label': 'category'
    }

data = pd.read_csv(
        './final_dataset.csv',
        parse_dates=['Timestamp'],
        usecols=[*dtypes.keys(), 'Timestamp'],
        engine='c',
        low_memory=True,
        na_values=np.inf
    )

In [3]:
data_prep.clean_data(data)

,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,14447,4504,14620,80,6,1291624472000000000,3974862,29,44,86.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,14447,4504,14620,80,6,1291624476000000000,63,1,1,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,14447,4505,14620,80,6,1291624476000000000,476078,2,6,86.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,14447,4505,14620,80,6,1291624477000000000,151,2,1,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,14447,4506,14620,80,6,1291624477000000000,472507,2,5,73.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12794622,17388,80,7979,53598,6,1519103692000000000,50,1,1,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12794623,9172,54599,2029,443,6,1519096115000000000,306,3,0,46.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12794624,8900,61087,7608,53,17,1519088599000000000,362,1,1,45.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12794625,9109,61580,7608,53,17,1519130591000000000,303,1,1,47.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12794626,8937,49393,7012,80,6,1519120540000000000,54,2,0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0